name = 'charge-companion-backend'
main = "src/index.ts"
compatibility_date = "2024-04-01"

[[d1_databases]]
binding = "DB"
database_name = "charger-companion-db"
database_id = "c51f1e9e-082f-4415-8f6d-d9ca575c8f2a"

[triggers]
crons = ["* * * * *"]

[vars]
# Add env variables here if needed

[[kv_namespaces]]
binding = "KV"
id = "cf6d4d38fc7949819033aa61ed01bfe7"
